### ISSUE TITLE
Streaming decoder hung

### ISSUE THREAD

**Issue by n3integration** [francoispqt/gojay#114]
First, thank you for your work on gojay. I am seeing a 2-3x performance improvement over the standard library. 

I encountered what I thought was a deadlock in the streaming decoder, but after further debugging I found that the process was not hung. Instead, the buffer size had been reduced to zero, which brought the streaming decoder to a screeching halt. I was going to submit a pull request, but noticed e5b786c9100c29947ac368300c0fe0dacc00c695 in the list of commits.  

When using go modules, the broken version is the version that all new projects will pull in as a dependency. Any chance a new release could be built to prevent others from running into this issue?

**Comment by francoispqt** [comment]
Hi, sorry for the delay, I've been very busy lately. 

I will push an update of the go modules.

**Comment by n3integration** [comment]
No worries. Thank you, sir.

**Comment by francoispqt** [comment]
Dependencies have been fixed with #117 

I'm closing the issue. Please ask to reopen if it doesn't work. 

Cheers
