### ISSUE TITLE
Bug: go install not working

### ISSUE THREAD

**Issue by marcsantiago** [francoispqt/gojay#115]
When using the command
go install github.com/francoispqt/gojay/gojay

This error is returned

# github.com/viant/toolbox
../../../viant/toolbox/yaml.go:13:10: undefined: yaml.NewEncoder

Mac go version
go version go1.12.5 darwin/amd64

**Comment by francoispqt** [comment]
Hey, I have updarted dependencies with #117 

Please let me know if it does not work.

Thanks

**Comment by marcsantiago** [comment]
It does work. The issue was with Go not updating dependencies the solution that was to run the command like this

➜  ~ go get -u gopkg.in/yaml.v2
➜  ~ go get github.com/viant/toolbox
➜  ~ go install github.com/francoispqt/gojay/gojay

where I must have had an old copy yaml.v2 that did not define `yaml.NewEncoder`
