### ISSUE TITLE
Usafe use of unsafe that leads to data corruption

### ISSUE THREAD

**Issue by rvasily** [francoispqt/gojay#3]
This library main perfomance gain based in unsafe hack in decoding strings:

https://github.com/francoispqt/gojay/blob/cce191b2eaf5400d428bf8cb841202ae27fb03c2/decode_string.go#L23-L25

It's will lead to very hard debugging problems with data corruption in some use cases with reuse raw data source bytes.

This behaviour must be specified in the documentation, becuse it's limits library usege ( as general purpose decoder replacement )  and makes benchmarks not really fair.

Here is th demo:
```golang
package main

import (
	"bytes"
	"fmt"
	"github.com/francoispqt/gojay"
	"net/http"
	"net/http/httptest"
	"sync"
)

var (
	users   = []*user{}
	bufPool = sync.Pool{
		New: func() interface{} {
			// this line must be printed once
			// to be sure that we reuse previous buffer
			fmt.Println("make new buf")
			return bytes.NewBuffer(make([]byte, 0, 64))
		},
	}
)

type user struct {
	email string
}

func (u *user) UnmarshalObject(dec *gojay.Decoder, key string) error {
	switch key {
	case "email":
		return dec.AddString(&u.email)
	}
	return nil
}

func (u *user) NKeys() int {
	return 1
}

func main() {
	postData := bytes.NewBufferString(`{"id":1,"name":"gojay","email":"gojay@email.com"}`)
	req := httptest.NewRequest("POST", "http://example.com/", postData)
	w := httptest.NewRecorder()
	ProcessUser(w, req)

	postData = bytes.NewBufferString(`{"id":1,"name":"go","email":"gojay@email.com"}`)
	req = httptest.NewRequest("POST", "http://example.com/", postData)
	w = httptest.NewRecorder()
	ProcessUser(w, req)

	// ----------------------------------
	// expected equal users
	fmt.Println(users[0], users[1])
	// got
	// &{ay@email.com"}m} &{gojay@email.com}
	// ----------------------------------
}

func ProcessUser(w http.ResponseWriter, r *http.Request) {
	buf := bufPool.Get().(*bytes.Buffer)
	buf.Reset() // now we will reuse same bytes buffer from previous request

	// users[0].email (previous user) uses memory from this buffer underliying bytes
	// overriding it will corrupt users[0].email
	// because now there will be different data
	buf.ReadFrom(r.Body)
	defer r.Body.Close()

	newUser := &user{}
	gojay.UnmarshalObject(buf.Bytes(), newUser)
	users = append(users, newUser)

	bufPool.Put(buf)
}

```

**Comment by francoispqt** [comment]
Thanks for the feedback. This is a know side effect. We should definitely add it to the documentation. 

Note that using the `Decoder` api is safer because it keeps its own buffer internally and io.Reader must use copy. So using:
```go
newUser := &user{}
dec := gojay.NewDecoder(strings.NewReader(`{"id":1,"name":"go","email":"gojay@email.com"}`))
dec.DecodeObjec(newUser)
```

Although, in order to keep the `Unmarshal` api safe, I have 3 solutions in mind: 
1.  We could use unsafe only if a specific config is set or by using `gojay.Unsafe.UnmarshalObjec()` for example. 
2. Copy the given buffer into the internal buffer at the beginning, 
3. Just not using unsafe at all. 

I have tested and benchmarked point 2 and 3. Copying the buffer is faster and results in less allocations. 

What do you suggest?

**Comment by francoispqt** [comment]
I have made changes copying the buffer at the beginning in the standard API and added an Unsafe api to a new branch. Will add details to documentation and merge the branch. Those changes are in branch `update/make-unmarshal-api-safer-for-strings` https://github.com/francoispqt/gojay/tree/update/make-unmarshal-api-safer-for-strings

**Comment by francoispqt** [comment]
Just merged the branch. Still working on making standard API safer and adding an explicit `Unsafe` api. Docs have been updated.
