### ISSUE TITLE
Doesn't respect omitempty on basic types

### ISSUE THREAD

**Issue by veqryn** [francoispqt/gojay#49]
```go
type Stuff struct {
	Thing string `json:"thing,omitempty"`
}
```
Unfortunately the above struct still has its field marshaled even when it is empty.

**Comment by francoispqt** [comment]
Gojay does not work with json tags and does not rely on reflection. 

It uses methods on decoder/encoder to marshal/unmarshal properties, I suggest you read documentation first.

If you want to do omit empty you can use the omit empty methods on the `Encoder`. 
e.g:
```go 
func (t *SomeType) MarshalJSONObject(enc *gojay.Encoder) {
    enc.StringKeyOmitEmpty("someString", t.someString)
}
```
