### ISSUE TITLE
Code generation tool should fail if it can't generate code for any fields

### ISSUE THREAD

**Issue by veqryn** [francoispqt/gojay#52]
I ran the code generation tool against some of my structs, and discovered that it was missing several fields in the generated code.
The fields that were missing were Slices.

Yes, your documentation says those aren't supported.
But your code generation tool needs to at least output an error message for each non-supported public/exported field so that people don't assume everything is good.

**Comment by francoispqt** [comment]
The new generator does that. I'm closing this one.
