### ISSUE TITLE
Decoder is skipping validation for boolean values 

### ISSUE THREAD

**Issue by a8m** [francoispqt/gojay#6]
Running the following code with the std decoder will return an error: 
```go
func main() {
	var b bool
	log.Println(json.Unmarshal([]byte(`tttt`), &b))
}
```
However, running the "same" code with `gojay.Decoder` will return no error. which is not good.
```go
func main() {
	var b bool
	err := gojay.NewDecoder(strings.NewReader("tttt")).DecodeBool(&b)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(b)
}
```
Looks like the problem is [here](https://github.com/francoispqt/gojay/blob/master/decode_bool.go#L13-L24).

Thanks for your work, let me know if you need any help to address that.

**Comment by francoispqt** [comment]
Hey, thanks for your feedback. 

Yes currently, it doesn't check correctness of `null`, `true`, `false` values. I'm adding validation on the standard API and adding an explicit `Unsafe` API which will skip this validation. The Unsafe API should be used if you are sure that your input is a valid JSON. 

I just release version 0.9.1 which adds first shot of `Unsafe` API. 

And yes would love some help :)
