### ISSUE TITLE
Usage for structs that has interfaces as fields (`interface{}`)

### ISSUE THREAD

**Issue by afiune** [francoispqt/gojay#62]
There are some cases where the JSON data could have different shapes, in those cases we would use an `interface{}` to define a field within a struct.

Is it possible for gojay to Decode fields of a struct that are `interfaces{}`?

As for instance, this example of an error that has a description with a number of sections that could have different shapes:
```go
type Error struct {
	Class       string               `json:"class"`
	Message     string               `json:"message"`
	Backtrace   []string             `json:"backtrace"`
	Description Description          `json:"description"`
}
type Description struct {
	Title    string                   `json:"title"`
	Sections []map[string]interface{} `json:"sections"`
}
```

How would you implement the `UnmarshalJSONObject()` function?

**Comment by francoispqt** [comment]
So, yes there is no such way at the moment but we could add something that would use standard `encoding/json` to decode interface values.

**Comment by afiune** [comment]
I thought about both alternatives, let me try to work on the first one since the second one, as you said, will require more time for its implementation.

Is this something you are accepting pull requests?

**Comment by francoispqt** [comment]
Yes of course, I'm happy to have contributions :)

**Comment by afiune** [comment]
Oh cool, I'll work on it.

![tenor-227593374](https://user-images.githubusercontent.com/5712253/44416650-b87fb780-a573-11e8-8015-32fc6307d38a.gif)
