### ISSUE TITLE
Invalid JSON, wrong char ':' found at position xxxx

### ISSUE THREAD

**Issue by marcopaganini** [francoispqt/gojay#76]
Hello,

I'm trying to parse a simple JSON file and somehow it always gives me an Invalid JSON message. Other parsers work fine. I'm unsure if this is a bug in gojay of if I'm doing something wrong.

I'm attaching a simple program that shows the problem:
[gojay.go.gz](https://github.com/francoispqt/gojay/files/2386902/gojay.go.gz)

The source is also available here for immediate viewing:
https://repl.it/@marcopaganini/GojayUnableToParse

(Unfortunately, repl.it does not allow loading external libraries, so it's impossible to run it there).

**Comment by francoispqt** [comment]
Within an `UnmarshalJSONArray` or `UnmarshalJSONObject` don't use `dec.DecodeObject` or `dec.DecodeArray` but use `dec.Object` or `dec.Array`.

**Comment by francoispqt** [comment]
`dec.AddXXX` and `dec.XXX` are basically the same (they parse keys/values inside objects/arrays) while `dec.DecodeXXX` are top level methods (they decode a whole JSON). Yes I agree that documentation can be slightly  reworked in that regard. I'd be very happy if you submit a PR :)

Thanks

**Comment by marcopaganini** [comment]
Excellent, thanks. I'll certainly send you a few PRs. I'm closing this bug. Thanks again.
