### ISSUE TITLE
concurrent unsafety of gojay.Marshal is not clearly documented

### ISSUE THREAD

**Issue by neex** [francoispqt/gojay#83]
Hello,

I think that the fact that `gojay.Marshal` is not safe for concurrent usage from multiple goroutines should be explicitly mentioned both in the readme and godoc.

Now it is stated that `Marshal` borrows an encoder and releases it back no matter what. While an attentive reader will have realised that it introduces a race (because same encoder could be reused by another goroutine and the buffer will get corrupted), the race is easily overseen problem as everything seems to be working most of the time, so it should be mentioned (may be even in bold and with some exclamation marks).

Example program that shows the race exists:

```golang
package main

import (
	"log"
	"strconv"
	"time"

	"github.com/francoispqt/gojay"
)

func proeb(num int) {
	for {
		b, err := gojay.Marshal(num)
		if err != nil {
			log.Fatal(err)
		}

		s := string(b)
		if n, err := strconv.Atoi(s); err != nil || n != num {
			log.Printf("caught race: %v %v", s, num)
		}
	}
}

func main() {
	for i := 0; i < 100; i++ {
		go proeb(i)
	}
	time.Sleep(100 * time.Second)
}
```

**Comment by francoispqt** [comment]
This is correct, I have just pushed a fix to master which effectively creates a new buffer when borrowing. Previously it was doing `enc.buf = enc.buf[:0]` which is wrong. I am patching versions with the fix.

If the fix works for you, please close the issue.

**Comment by neex** [comment]
I thought it was the intended behaviour, just not documented.

Thanks for the fix!
