### ISSUE TITLE
Gojay supports for sql.Nulls but does not generate them

### ISSUE THREAD

**Issue by OGKevin** [francoispqt/gojay#99]
Currently, one could use `sql.Null..` to encode/decode structs.

e.g
```golang
	DB           sql.NullString `gojay:"db"`

	enc.SQLNullStringKey("db", &v.DB)
```

however, when a struct with such field gets generated via the Gojay gen tool, the bindings for these fields are not generated.

**Comment by francoispqt** [comment]
Hi, I have just finished replacing the code generation tool completely with the help of another contributor. I have merged it to master. It now supports generating `time.Time`, `sql.Nulls`, can also generate `sync.Pool` and slices on the fly. You can find the doc for the new tool here: https://github.com/francoispqt/gojay/tree/master/gojay.

Sorry for not answering earlier, I was very these pas few weeks. 

Thanks

**Comment by OGKevin** [comment]
@francoispqt thanks for the reply, i'll certainly give the new generator a try :)
